#!/bin/sh
# FIX permission for volumes.

chown nobody /data
chown nobody /app -R

sudo -u nobody /app/nextcloud/occ config:system:get installed
needinstall=$?
if [ $needinstall ]; then
 echo "configuranding nextcloud"
 cd /app/nextcloud
 echo  -n "wait db ";
 while 	! nc -z -w 4 db 3306; do
	echo -n ".";
	sleep 1;
 done
 
 echo " ready";

 sudo -u nobody /app/nextcloud/occ  maintenance:install \
	--database "mysql" \
	--database-host "db" \
	--database-name "nextcloud" \
	--database-user "root" \
	--database-pass "secret" \
	--admin-user "admin" \
	--admin-pass "secret" \
	--data-dir=/data

 sudo -u nobody /app/nextcloud/occ upgrade
 sudo -u nobody /app/nextcloud/occ app:enable galleryplus
 sudo -u nobody /app/nextcloud/occ app:enable documents
 sudo -u nobody /app/nextcloud/occ config:system:set defaultapp --value=activity
 sudo -u nobody /app/nextcloud/occ config:system:set trusted_domain --value=127.0.0.1
 sudo -u nobody /app/nextcloud/occ config:system:set filelocking.enabled --value='true'
 sudo -u nobody /app/nextcloud/occ config:system:set memcache.local --value='\OC\Memcache\APCu'

fi
COUNTER=300
while true; do
	COUNTER=$((COUNTER+1))
	if [ $COUNTER -gt 300 ]; then
		sudo -u nobody php  /app/nextcloud/cron.php
		COUNTER=0
	fi
	sleep 1
done
