FROM alpine:3.5

RUN apk add --update \
	php5-zip \
	php5-gd \
	php5-cli \
	php5-pdo_mysql \
	php5-json \
	php5-posix \
	php5-dom \
	php5-xmlreader \
	php5-xml \
	php5-ctype \
	php5-curl \
	php5-zlib \
	php5-pcntl \
	php5-openssl \
	php5-apcu \
	php5-ldap \
	php5-opcache

